//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_usl
    {
        public int id_client { get; set; }
        public string familia { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public string usl_title { get; set; }
        public string stat_title { get; set; }
        public int id_usl { get; set; }
        public int id_stat { get; set; }
    }
}
