//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id_client { get; set; }
        public string familia { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public string address_reg { get; set; }
        public string snils { get; set; }
        public Nullable<int> id_udost { get; set; }
        public string nomer_udost { get; set; }
        public Nullable<int> id_usl { get; set; }
        public Nullable<int> id_family { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> id_stat { get; set; }
        public Nullable<bool> was_select { get; set; }
        public Nullable<int> id_poshlina { get; set; }
        public Nullable<bool> oplata { get; set; }
        public Nullable<int> id_med { get; set; }
        public string nomer_med { get; set; }
        public Nullable<int> id_svidet { get; set; }
        public string nomer_svedet { get; set; }
        public Nullable<bool> photo { get; set; }
        public string nomer_predstavit { get; set; }
        public Nullable<int> id_comp { get; set; }
    
        public virtual Comp_strah Comp_strah { get; set; }
        public virtual Family Family { get; set; }
        public virtual Med_spravka Med_spravka { get; set; }
        public virtual Poshlina Poshlina { get; set; }
        public virtual Status Status { get; set; }
        public virtual Svidet Svidet { get; set; }
        public virtual Udost_lich Udost_lich { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
